spring:
  datasource:
    url: jdbc:h2:mem:renegociacao
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    locations: classpath:db/migration

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true