spring:
  datasource:
    url: jdbc:h2:mem:renegociacao-produto
    driverClassName: org.h2.Driver
    username: sa
    password: sa

eureka:
  client:
    serviceUrl:
      defaultZone: http://renegociacao-discovery:8761/eureka/