spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://renegociacao-produto-mysql:3306/renegociacao-produto
    username: root
    password: root

eureka:
  client:
    serviceUrl:
      defaultZone: http://renegociacao-discovery:8761/eureka/