spring:
  datasource:
    url: jdbc:h2:mem:renegociacao_produto
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  flyway:
    locations: classpath:db/migration,classpath:db/testdata
    
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20